force-app/main/default/objects/ExtensionConfiguration__c/ExtensionConfiguration__c.object-meta.xml
<CustomObject>
    <description>Defines the configuration for a specific extension.</description>
    <label>Extension Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extension Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtensionConfiguration__c/fields/ExtensionTool__c.field-meta.xml
<CustomField>
    <fullName>ExtensionTool__c</fullName>
    <label>Extension Tool</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual Tests</fullName>
            </value>
            <value>
                <fullName>PMD</fullName>
            </value>
            <value>
                <fullName>Copado Robotic Test</fullName>
                <isActive>false</isActive>
                <label>Copado Robotic Test</label>
            </value>
            <value>
                <fullName>MC Mock Tool</fullName>
                <isActive>false</isActive>
                <label>MC Mock Tool</label>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Job Step.</description>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;,
  IF(IsSkipped__c , &apos;Skipped&apos;,
    IF(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c))))</formula>
    <inlineHelpText>The status of the Job Step.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <description>A job template is a reusable template with a list of steps that can be executed as part of different processes such as a commit, a promotion or a deployment.</description>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestExecutionMonitorCtrlTest.cls
@isTest
private class TestExecutionMonitorCtrlTest {
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void getExecutionDetails() {
        System.runAs(getUser()) {
            //SETUP
            Test__c test = getTest();

            //Exercise
            TestExecutionMonitorCtrl.ExecutionDetails details = TestExecutionMonitorCtrl.getExecutionDetails(test.Id);

            //VERIFY
            assertTest(test, details);
        }
    }

    @isTest
    private static void getExecutionDetailsWithEmptyJob() {
        System.runAs(getUser()) {
            //SETUP
            Test__c test = getTest();
            test.LatestJobExecution__c = null;
            update test;

            //Exercise
            TestExecutionMonitorCtrl.ExecutionDetails details = TestExecutionMonitorCtrl.getExecutionDetails(test.Id);

            //VERIFY

            System.assertEquals(true, details == null, 'Execution Details should be null');
        }
    }

    @isTest
    private static void getExecutionDetailsWithNullTest() {
        System.runAs(getUser()) {
            //Exercise
            TestExecutionMonitorCtrl.ExecutionDetails details = TestExecutionMonitorCtrl.getExecutionDetails(null);

            //VERIFY
            System.assertEquals(true, details == null, 'Execution Details should be null');
        }
    }

    private static void assertTest(Test__c test, TestExecutionMonitorCtrl.ExecutionDetails executionDetails) {
        System.assertEquals(true, executionDetails != null, 'Execution Details can not be null');
        System.assertEquals(
            test.LatestJobExecution__c,
            executionDetails.id,
            'Expected ' +
            test.LatestJobExecution__c +
            ' but found ' +
            executionDetails.id
        );
        System.assertEquals(
            test.LatestJobExecution__r.Name,
            executionDetails.name,
            'Expected ' +
            test.LatestJobExecution__r.Name +
            ' but found ' +
            executionDetails.name
        );
        System.assertEquals(
            test.LatestJobExecution__r.Status__c,
            executionDetails.status,
            'Expected ' +
            test.LatestJobExecution__r.Status__c +
            ' but found ' +
            executionDetails.status
        );
    }

    @TestSetup
    private static void setupData() {
        insertData();
    }

    private static void insertData() {
        System.runAs(createTestUserWithPermissionSets()) {
            ExtensionConfiguration__c extensionConfig = createExtensionConfigurations();
            Test__c test = createTest(extensionConfig.Id);

            JobExecution__c jobExecution = createJob();

            test.LatestJobExecution__c = jobExecution.Id;
            update test;
        }
    }

    private static User createTestUserWithPermissionSets() {
        User result = TestDataFactory.createUsers()[0];

        List<PermissionSet> permissionSets = [SELECT Id FROM PermissionSet WHERE Name IN ('Copado_User', 'Copado_Functions', 'Copado_Job_Engine')];
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
        for (PermissionSet permissionSet : permissionSets) {
            assignments.add(new PermissionSetAssignment(AssigneeId = result.Id, PermissionSetId = permissionSet.Id));
        }
        insert assignments;

        return result;
    }

    private static ExtensionConfiguration__c createExtensionConfigurations() {
        ExtensionConfiguration__c extensionConfig = new ExtensionConfiguration__c(
            Name = 'Test',
            ExtensionApplication__c = 'Test',
            ExtensionTool__c = 'Manual Tests',
            Active__c = true
        );
        insert extensionConfig;
        return extensionConfig;
    }

    private static Test__c createTest(Id extensionConfigId) {
        Test__c test = new Test__c(Name = 'Mock Test', ExtensionConfiguration__c = extensionConfigId);

        insert test;
        return test;
    }

    private static JobExecution__c createJob() {
        JobTemplate__c template = new JobTemplate__c();
        template.Name = 'Sample';
        template.Version__c = 1;
        insert template;

        JobStep__c step = new JobStep__c(Name = 'step3', JobTemplate__c = template.Id, Type__c = 'Manual', Order__c = 1);
        insert step;

        JobExecution__c execution = new JobExecution__c();
        execution.Template__c = template.Id;
        insert execution;
        return execution;
    }

    private static Test__c getTest() {
        return [SELECT Id, LatestJobExecution__c, LatestJobExecution__r.Name, LatestJobExecution__r.Status__C FROM Test__c LIMIT 1];
    }

    private static User getUser() {
        return [SELECT Id, Name, LastName, Email, Username FROM User WHERE Email = 'test1@test1.com' LIMIT 1];
    }
}